version: '3'

services:
  mongodb_container:
    image: mongo
    container_name: mongodb-container
    restart: unless-stopped
    command: mongod
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/docker/volumes/156f6f74ef9c245068cfc87670dc19fe93548ee2ab8114aff757ea250b65cff9/_data:/data/configdb
      - /var/lib/docker/volumes/mongodb-data/_data:/data/db
    networks:
      - ContainDB-Network
  mysql_container:
    image: mysql
    container_name: mysql-container
    restart: unless-stopped
    command: mysqld
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'Ankan@157'
      MYSQL_MAJOR: 'innovation'
      MYSQL_VERSION: '9.3.0-1.el9'
      MYSQL_SHELL_VERSION: '9.3.0-1.el9'

    volumes:
      - /var/lib/docker/volumes/mysql-data/_data:/var/lib/mysql
    networks:
      - ContainDB-Network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    command: apache2-foreground
    ports:
      - "8080:80"
    environment:
      PMA_HOST: 'mysql-container'

    networks:
      - ContainDB-Network

networks:
  ContainDB-Network:
    external: true